import { useState, useEffect, useCallback, useRef } from 'react';
import { Card, Row, Col, Typography, Progress, Tag, Space, Empty, Spin, Button, Statistic, Divider, Tabs, Modal, Skeleton, message } from 'antd';
import {
  RadarChartOutlined, AlertOutlined, SmileOutlined,
  ThunderboltOutlined, CloudOutlined, BulbOutlined, ClockCircleOutlined,
  CrownOutlined, StarOutlined, CheckCircleOutlined,
} from '@ant-design/icons';
import { RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { profileApi } from '../../services';
import api from '../../services/api';

const { Title, Text, Paragraph } = Typography;

const riskColors: Record<string, string> = { LOW: '#52c41a', MEDIUM: '#faad14', HIGH: '#ff4d4f', CRISIS: '#cf1322' };
const riskLabels: Record<string, string> = { LOW: '低风险', MEDIUM: '中风险', HIGH: '高风险', CRISIS: '危机' };

export default function Profile() {
  const [profile, setProfile] = useState<any>(null);
  const [moodTrend, setMoodTrend] = useState<any[]>([]);
  const [dynamicProfile, setDynamicProfile] = useState<any>(null);
  const [copingStrategies, setCopingStrategies] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [updating, setUpdating] = useState(false);
  const autoGeneratedRef = useRef(false);
  const [membership, setMembership] = useState<any>(null);
  const [upgradeModal, setUpgradeModal] = useState(false);
  const [payModal, setPayModal] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState<any>(null);
  const [payLoading, setPayLoading] = useState(false);
  const [genProgress, setGenProgress] = useState(0);

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const [profileRes, trendRes, emotionRes, copingRes] = await Promise.all([
        profileApi.getPsychological() as any,
        profileApi.getMoodTrend(30) as any,
        profileApi.getTodayEmotionalState() as any,
        profileApi.getCopingStrategies() as any,
      ]);
      setProfile(profileRes.data);
      setMoodTrend(trendRes.data?.moodRecords || []);
      setDynamicProfile(emotionRes.data);
      setCopingStrategies(copingRes.data);

      // 获取会员信息
      try {
        const memberRes = await api.get('/profile/membership') as any;
        setMembership(memberRes.data);
      } catch {}
    } catch {} finally { setLoading(false); }
  }, []);

  const handleUpgrade = (plan: any) => {
    setSelectedPlan(plan);
    setPayModal(true);
  };

  const handleConfirmPay = async () => {
    setPayLoading(true);
    // 模拟支付流程
    await new Promise(resolve => setTimeout(resolve, 2000));
    try {
      await api.put('/profile/membership', { membershipType: selectedPlan.type });
      setMembership({ membershipType: selectedPlan.type, membershipExpiresAt: new Date(Date.now() + 30 * 86400000).toISOString() });
      message.success(`已升级为${selectedPlan.name}，有效期30天`);
      setPayModal(false);
      setUpgradeModal(false);
    } catch {
      message.error('升级失败');
    } finally {
      setPayLoading(false);
    }
  };

  const handleUpdate = useCallback(async () => {
    setUpdating(true);
    try {
      await profileApi.updateProfile();
    } catch {} finally { setUpdating(false); }
  }, []);

  // 初始加载
  useEffect(() => { loadData(); }, [loadData]);

  // 生成完后重新加载数据
  useEffect(() => {
    if (!updating && autoGeneratedRef.current) {
      loadData();
    }
  }, [updating, loadData]);

  // 如果没有画像且未自动生成过，自动触发一次
  useEffect(() => {
    if (!profile && !loading && !updating && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      // 模拟进度条，让用户感知到进展
      let p = 0;
      const timer = setInterval(() => {
        p = Math.min(p + Math.random() * 8, 90);
        setGenProgress(Math.round(p));
      }, 1000);
      handleUpdate().finally(() => {
        clearInterval(timer);
        setGenProgress(100);
      });
    }
  }, [profile, loading, updating, handleUpdate]);

  // 骨架屏加载状态
  if (loading && !profile) {
    return (
      <div>
        {/* 会员卡片骨架 */}
        <Skeleton.Avatar active size={64} style={{ marginBottom: 16 }} />
        <Skeleton.Input active style={{ width: 200, marginBottom: 24, display: 'block' }} />
        
        <Row gutter={[16, 16]}>
          <Col xs={24} md={8}>
            <Card style={{ borderRadius: 12, textAlign: 'center' }}>
              <Skeleton.Avatar active size={120} shape="square" style={{ borderRadius: 60 }} />
              <Skeleton.Button active style={{ marginTop: 16, width: 100 }} />
            </Card>
          </Col>
          <Col xs={24} md={16}>
            <Card title={<Skeleton.Input active size="small" style={{ width: 120 }} />} style={{ borderRadius: 12 }}>
              <Skeleton.Image active style={{ height: 280 }} />
            </Card>
          </Col>
          <Col xs={24}>
            <Card title={<Skeleton.Input active size="small" style={{ width: 150 }} />} style={{ borderRadius: 12 }}>
              <Skeleton.Image active style={{ height: 250 }} />
            </Card>
          </Col>
        </Row>
      </div>
    );
  }

  if (loading) return (
    <div style={{ textAlign: 'center', padding: 100 }}>
      <Spin size="large" />
      <div style={{ marginTop: 16 }}><Text type="secondary">正在刷新数据...</Text></div>
    </div>
  );

  if (!profile) {
    return (
      <Card style={{ borderRadius: 12, textAlign: 'center', padding: '60px 40px' }}>
        <div style={{ fontSize: 48, marginBottom: 16 }}>🧠</div>
        <Title level={4} style={{ marginBottom: 8 }}>AI 正在分析你的心理状态</Title>
        <Text type="secondary" style={{ display: 'block', marginBottom: 24 }}>
          综合你的对话记录、测评结果和情绪数据，生成专属心理画像
        </Text>
        <div style={{ maxWidth: 400, margin: '0 auto' }}>
          <Progress percent={genProgress} strokeColor={{ from: '#6366f1', to: '#ec4899' }} />
          <div style={{ marginTop: 12 }}>
            <Text type="secondary" style={{ fontSize: 12 }}>
              {genProgress < 30 ? ' 收集对话数据...' :
               genProgress < 60 ? '🔍 分析情绪趋势...' :
               genProgress < 90 ? '🧩 生成心理维度评分...' :
               '✨ 即将完成...'}
            </Text>
          </div>
        </div>
      </Card>
    );
  }

  const radarData = [
    { subject: '焦虑', value: profile.anxiety },
    { subject: '抑郁', value: profile.depression },
    { subject: '压力', value: profile.stress },
    { subject: '睡眠', value: profile.sleepQuality },
    { subject: '社交', value: profile.socialActivity },
    { subject: '情绪稳定', value: profile.emotionalStability },
  ];

  const membershipInfo: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
    FREE: { label: '免费版', color: '#8c8c8c', icon: <StarOutlined /> },
    BASIC: { label: '基础版', color: '#1890ff', icon: <CrownOutlined /> },
    PREMIUM: { label: '高级版', color: '#fa8c16', icon: <CrownOutlined style={{ color: '#fa8c16' }} /> },
  };

  const currentMembership = membershipInfo[membership?.membershipType || 'FREE'] || membershipInfo.FREE;
  const isExpired = membership?.membershipExpiresAt && new Date(membership.membershipExpiresAt) < new Date();

  return (
    <div>
      {/* 会员状态卡片 */}
      <Card style={{
        borderRadius: 16, marginBottom: 24,
        background: membership?.membershipType === 'PREMIUM' ? 'linear-gradient(135deg, #fa8c16 0%, #faad14 100%)'
          : membership?.membershipType === 'BASIC' ? 'linear-gradient(135deg, #1890ff 0%, #69c0ff 100%)'
          : 'linear-gradient(135deg, #f5f5f5 0%, #e8e8e8 100%)',
        border: 'none',
      }}>
        <Row align="middle">
          <Col flex="auto">
            <Space>
              {currentMembership.icon}
              <Text strong style={{ fontSize: 18, color: membership?.membershipType === 'FREE' ? '#595959' : '#fff' }}>
                {currentMembership.label}
              </Text>
            </Space>
            {membership?.membershipExpiresAt && !isExpired && (
              <div style={{ marginTop: 4 }}>
                <Text style={{ fontSize: 13, color: membership?.membershipType === 'FREE' ? '#8c8c8c' : 'rgba(255,255,255,0.8)' }}>
                  有效期至 {new Date(membership.membershipExpiresAt).toLocaleDateString()}
                </Text>
              </div>
            )}
            {isExpired && (
              <div style={{ marginTop: 4 }}>
                <Text style={{ fontSize: 13, color: '#ff4d4f' }}>会员已过期</Text>
              </div>
            )}
          </Col>
          <Col>
            <Button type="primary" ghost onClick={() => setUpgradeModal(true)}
              style={{ borderColor: membership?.membershipType === 'FREE' ? '#d9d9d9' : '#fff', color: membership?.membershipType === 'FREE' ? '#595959' : '#fff' }}>
              {membership?.membershipType === 'PREMIUM' ? '续费' : '升级会员'}
            </Button>
          </Col>
        </Row>
      </Card>

      <Row gutter={[16, 16]}>
        {/* 综合评分 */}
        <Col xs={24} md={8}>
          <Card style={{ borderRadius: 12, textAlign: 'center' }}>
            <Title level={5}>综合心理健康评分</Title>
            <Progress type="dashboard" percent={profile.overallScore} format={(p) => (
              <div>
                <div style={{ fontSize: 32, fontWeight: 'bold' }}>{p}</div>
                <Text type="secondary">/ 100</Text>
              </div>
            )} strokeColor={profile.overallScore > 60 ? '#52c41a' : profile.overallScore > 30 ? '#faad14' : '#ff4d4f'} />
            <div style={{ marginTop: 16 }}>
              <Tag color={riskColors[profile.riskLevel]} style={{ fontSize: 14, padding: '4px 12px' }}>
                {riskLabels[profile.riskLevel]}
              </Tag>
            </div>
            <Button onClick={handleUpdate} loading={updating} style={{ marginTop: 16 }}>
              更新画像
            </Button>
          </Card>
        </Col>

        {/* 雷达图 */}
        <Col xs={24} md={16}>
          <Card title={<Space><RadarChartOutlined /> 心理维度分析</Space>} style={{ borderRadius: 12 }}>
            <ResponsiveContainer width="100%" height={280}>
              <RadarChart data={radarData}>
                <PolarGrid />
                <PolarAngleAxis dataKey="subject" />
                <PolarRadiusAxis angle={30} domain={[0, 100]} />
                <Radar name="评分" dataKey="value" stroke="#6366f1" fill="#6366f1" fillOpacity={0.3} />
              </RadarChart>
            </ResponsiveContainer>
          </Card>
        </Col>

        {/* 情绪趋势 */}
        <Col xs={24}>
          <Card title={<Space><SmileOutlined /> 情绪趋势 (近30天)</Space>} style={{ borderRadius: 12 }}>
            {moodTrend.length > 0 ? (
              <ResponsiveContainer width="100%" height={250}>
                <LineChart data={moodTrend.map((r: any) => ({ date: r.recordedAt?.slice(5, 10), score: r.score }))}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="date" />
                  <YAxis domain={[0, 10]} />
                  <Tooltip />
                  <Line type="monotone" dataKey="score" stroke="#6366f1" strokeWidth={2} dot={{ fill: '#6366f1' }} />
                </LineChart>
              </ResponsiveContainer>
            ) : <Empty description="暂无情绪记录" />}
          </Card>
        </Col>

        {/* AI 报告 */}
        {profile.report && (
          <Col xs={24}>
            <Card title={<Space><CloudOutlined /> AI 心理画像报告</Space>} style={{ borderRadius: 12 }}>
              <Paragraph style={{ whiteSpace: 'pre-wrap', lineHeight: 1.8 }}>{profile.report}</Paragraph>
              <Text type="secondary">评估方式：{profile.assessedBy} | 更新时间：{new Date(profile.updatedAt).toLocaleDateString()}</Text>
            </Card>
          </Col>
        )}

        {/* 动态情绪画像 */}
        {dynamicProfile?.hasData && dynamicProfile?.profile && (
          <Col xs={24}>
            <Card
              title={<Space><ThunderboltOutlined /> 今日动态情绪画像 <Tag color="purple">AI 实时分析</Tag></Space>}
              extra={dynamicProfile.updatedAt && <Text type="secondary" style={{ fontSize: 12 }}><ClockCircleOutlined /> {new Date(dynamicProfile.updatedAt).toLocaleString()}</Text>}
              style={{ borderRadius: 12 }}
            >
              <Row gutter={24}>
                <Col xs={24} md={8}>
                  <div style={{ textAlign: 'center' }}>
                    <Text type="secondary">今日主要情绪</Text>
                    <div style={{ fontSize: 24, fontWeight: 'bold', margin: '8px 0' }}>
                      {dynamicProfile.profile.dominantEmotions?.join('、') || '平静'}
                    </div>
                    <Tag color={riskColors[dynamicProfile.profile.riskLevel]} style={{ fontSize: 13, padding: '4px 12px' }}>
                      {riskLabels[dynamicProfile.profile.riskLevel]}
                    </Tag>
                    <div style={{ marginTop: 12 }}>
                      <Text type="secondary">情绪趋势：</Text>
                      <Text strong>{dynamicProfile.profile.emotionalTrend}</Text>
                    </div>
                  </div>
                </Col>
                <Col xs={24} md={16}>
                  <Row gutter={[12, 12]}>
                    {[
                      { label: '焦虑', value: dynamicProfile.profile.anxiety, color: '#ff4d4f' },
                      { label: '抑郁', value: dynamicProfile.profile.depression, color: '#722ed1' },
                      { label: '压力', value: dynamicProfile.profile.stress, color: '#fa8c16' },
                      { label: '睡眠', value: dynamicProfile.profile.sleepQuality, color: '#1890ff' },
                      { label: '社交', value: dynamicProfile.profile.socialActivity, color: '#52c41a' },
                      { label: '情绪稳定', value: dynamicProfile.profile.emotionalStability, color: '#13c2c2' },
                    ].map(({ label, value, color }) => (
                      <Col xs={12} key={label}>
                        <div style={{ marginBottom: 4 }}>
                          <Text type="secondary" style={{ fontSize: 12 }}>{label}</Text>
                          <Text style={{ float: 'right', fontWeight: 600, color }}>{value}</Text>
                        </div>
                        <Progress percent={value} showInfo={false} size="small" strokeColor={color} />
                      </Col>
                    ))}
                  </Row>
                </Col>
              </Row>
              <Divider style={{ margin: '16px 0' }} />
              <Paragraph style={{ fontSize: 14, lineHeight: 1.8 }}>{dynamicProfile.profile.emotionalSummary}</Paragraph>
            </Card>
          </Col>
        )}

        {/* 应对策略 */}
        {copingStrategies && (
          <Col xs={24}>
            <Card
              title={<Space><BulbOutlined /> 个性化应对策略</Space>}
              style={{ borderRadius: 12, background: 'linear-gradient(135deg, #f0f9ff 0%, #f5f3ff 100%)' }}
            >
              <Row gutter={16}>
                <Col xs={24} md={8}>
                  <Card size="small" title="当下可做" style={{ borderRadius: 8 }}>
                    {copingStrategies.immediateActions?.map((a: string, i: number) => (
                      <div key={i} style={{ padding: '4px 0', fontSize: 13 }}>• {a}</div>
                    ))}
                  </Card>
                </Col>
                <Col xs={24} md={8}>
                  <Card size="small" title="本周建议" style={{ borderRadius: 8 }}>
                    {copingStrategies.shortTermStrategies?.map((s: string, i: number) => (
                      <div key={i} style={{ padding: '4px 0', fontSize: 13 }}>• {s}</div>
                    ))}
                  </Card>
                </Col>
                <Col xs={24} md={8}>
                  <Card size="small" title="长期方向" style={{ borderRadius: 8 }}>
                    {copingStrategies.longTermSuggestions?.map((s: string, i: number) => (
                      <div key={i} style={{ padding: '4px 0', fontSize: 13 }}>• {s}</div>
                    ))}
                  </Card>
                </Col>
              </Row>
              <div style={{ marginTop: 16, padding: '12px 16px', background: '#fff7e6', borderRadius: 8, textAlign: 'center' }}>
                <Text style={{ fontSize: 15, color: '#d46b08', fontWeight: 500 }}>{copingStrategies.encouragingMessage}</Text>
              </div>
            </Card>
          </Col>
        )}
      </Row>

      {/* 升级会员弹窗 */}
      <Modal open={upgradeModal} onCancel={() => setUpgradeModal(false)} title="升级会员" footer={null} width={640}>
        <Row gutter={16}>
          {[
            { type: 'FREE', name: '免费版', price: 0, features: ['AI 咨询', '基础测评', '社区互助'], color: '#f5f5f5', textColor: '#595959' },
            { type: 'BASIC', name: '基础版', price: 29, features: ['AI 咨询无限次', '高级测评', '情绪追踪', '疗愈内容'], color: '#e6f7ff', textColor: '#1890ff' },
            { type: 'PREMIUM', name: '高级版', price: 99, features: ['全部基础版功能', '专家预约优先', '个性化方案', '危机干预', '专属客服'], color: '#fff7e6', textColor: '#fa8c16' },
          ].map((plan) => (
            <Col xs={24} sm={8} key={plan.type}>
              <Card style={{
                borderRadius: 12, textAlign: 'center',
                background: plan.color, border: `2px solid ${plan.textColor}`,
                opacity: membership?.membershipType === plan.type ? 0.6 : 1,
              }}>
                <Title level={5} style={{ color: plan.textColor }}>{plan.name}</Title>
                <div style={{ fontSize: 28, fontWeight: 'bold', color: plan.textColor, margin: '8px 0' }}>
                  {plan.price === 0 ? '免费' : `¥${plan.price}/月`}
                </div>
                <Divider style={{ margin: '12px 0' }} />
                {plan.features.map((f, i) => (
                  <div key={i} style={{ padding: '4px 0', fontSize: 13 }}>
                    <CheckCircleOutlined style={{ color: plan.textColor, marginRight: 6 }} />{f}
                  </div>
                ))}
                {membership?.membershipType !== plan.type && (
                  <Button type="primary" block style={{ marginTop: 16, background: plan.textColor, borderColor: plan.textColor, borderRadius: 20 }}
                    onClick={() => handleUpgrade(plan)}>
                    {plan.price === 0 ? '当前方案' : '立即升级'}
                  </Button>
                )}
                {membership?.membershipType === plan.type && (
                  <Tag color={plan.textColor} style={{ marginTop: 16, display: 'block' }}>当前方案</Tag>
                )}
              </Card>
            </Col>
          ))}
        </Row>
      </Modal>

      {/* 支付确认弹窗 */}
      <Modal
        open={payModal}
        onCancel={() => setPayModal(false)}
        title="确认升级"
        onOk={handleConfirmPay}
        okText="确认支付"
        cancelText="取消"
        confirmLoading={payLoading}
      >
        {selectedPlan && (
          <div style={{ padding: '16px 0' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
              <Text>升级方案：</Text>
              <Text strong style={{ color: selectedPlan.textColor }}>{selectedPlan.name}</Text>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
              <Text>支付金额：</Text>
              <Text strong style={{ fontSize: 20, color: '#ff4d4f' }}>¥{selectedPlan.price}/月</Text>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
              <Text>有效期：</Text>
              <Text>30 天</Text>
            </div>
            <Divider />
            <div style={{ background: '#f9f0ff', padding: 12, borderRadius: 8, textAlign: 'center' }}>
              <Text style={{ fontSize: 13, color: '#722ed1' }}>
                 模拟支付演示 — 点击确认支付后将立即生效
              </Text>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
